// import {} from "next/font/google";
import "./globals.css";
import Header from "../components/Header";
import Footer from "../components/Footer";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "NextJS",
  description: "Generated by create next app",
  openGraph: {
    type: "profile",
    firstName: "Gasser",
    lastName: "Elnaggar"
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased scrollbar-none`}>
      <body className="min-h-full flex flex-col">
        <Header />

        <main className="grow bg-black/10">{children}</main>

        <Footer />
      </body>
    </html>
  );
}
